services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${WIRECARD_POSTGRES_DB}
      POSTGRES_USER: ${WIRECARD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WIRECARD_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
